# Generated by Django 4.1.1 on 2022-09-13 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appmtv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familia',
            old_name='nombre_apellido',
            new_name='nombre',
        ),
    ]
